S=str(input("Introduceti sirul de caractere:"))
a=S.count('A')
print('Numarul de caract, "A" in sir: ', a)
b=S.replace("A", "*")
print('Substituirea caracterului A prin caract. *', b)
c=S.translate({ord('B'):None})
print('Sirul fara de caract. B: ', c)
d=S.count("MA")
print("Numarul de silabe MA in sir: ", d)
e=S.replace("MA", "TA")
print("Sirul unde MA este subst. de TA: ", e)
f=S.replace("TO",'')
print("Sirul fara de Silaba TO: ", f)
print("Forma inversa a sirului: ", S[::-1])